# q1 features

DIP_SWITCH_ENABLE = no 		# kill mac/win switch

BOOT_MAGIC = yes
CONSOLE_ENABLE = no
NKRO_ENABLE = yes
MOUSEKEY_ENABLE = no
TAP_DANCE_ENABLE = no
LTO_ENABLE = no
UCIS_ENABLE = no
COMMAND_ENABLE = yes
DEBUG_EEPROM = no
RGB_MATRIX_ENABLE = yes
CAPS_WORD_ENABLE = yes

