// drop alt v2
#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 5

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD 


// RGB stuffs
#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_DISABLE_WHEN_USB_SUSPENDED
